-- INSERT INTO USERS VALUES(2,'jamesbond','jamesbond@azuretraining.com',CURRENT_TIMESTAMP);

CREATE TABLE ORDERS (
    id INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT NOT NULL,
    PRODUCT_NAME NVARCHAR(255) NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    STATUS NVARCHAR(50) NOT NULL DEFAULT 'PENDING',
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETDATE()
);

-- Optional: Add index on USER_ID for better query performance
CREATE INDEX IX_ORDERS_USER_ID ON ORDERS (USER_ID);

-- Optional: Add index on STATUS for filtering orders by status
CREATE INDEX IX_ORDERS_STATUS ON ORDERS (STATUS);

-- Optional: Add index on CREATED_AT for date-based queries
CREATE INDEX IX_ORDERS_CREATED_AT ON ORDERS (CREATED_AT);

SELECT * FROM ORDERS;
